// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourismCMS.Data;

#nullable disable

namespace TourismCMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260406183301_RestoreOwnerIdToPOI")]
    partial class RestoreOwnerIdToPOI
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PoiCategory", b =>
                {
                    b.Property<int>("Poiid")
                        .HasColumnType("int")
                        .HasColumnName("POIID");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.HasKey("Poiid", "CategoryId")
                        .HasName("PK__POI_Cate__F3B9709DF94CC70B");

                    b.HasIndex("CategoryId");

                    b.ToTable("POI_Categories", (string)null);
                });

            modelBuilder.Entity("TourismCMS.Models.AdminUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId")
                        .HasName("PK__AdminUse__1788CCAC28FC9F8C");

                    b.HasIndex("RoleId");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("TourismCMS.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("LogId")
                        .HasName("PK__AuditLog__5E5499A81C6A02AB");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("TourismCMS.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A2B39B330C8");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("TourismCMS.Models.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MenuID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuId"));

                    b.Property<string>("FoodName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("Poiid")
                        .HasColumnType("int")
                        .HasColumnName("POIID");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.HasKey("MenuId")
                        .HasName("PK__Menu__C99ED250BB90BCE7");

                    b.HasIndex("Poiid");

                    b.ToTable("Menu", (string)null);
                });

            modelBuilder.Entity("TourismCMS.Models.POI", b =>
                {
                    b.Property<int>("Poiid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("POIID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Poiid"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Poiid")
                        .HasName("PK__POIs__5229E33F54FB0367");

                    b.ToTable("POIs", (string)null);
                });

            modelBuilder.Entity("TourismCMS.Models.PoiOwnerRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PoiOwnerRegistrations");
                });

            modelBuilder.Entity("TourismCMS.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3AB48E9454");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TourismCMS.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TourismCMS.Models.VisitLog", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VisitID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitId"));

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DeviceID");

                    b.Property<int?>("Poiid")
                        .HasColumnType("int")
                        .HasColumnName("POIID");

                    b.Property<DateTime?>("VisitTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("VisitId")
                        .HasName("PK__VisitLog__4D3AA1BE915D54F2");

                    b.HasIndex("Poiid");

                    b.ToTable("VisitLog", (string)null);
                });

            modelBuilder.Entity("PoiCategory", b =>
                {
                    b.HasOne("TourismCMS.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__POI_Categ__Categ__5535A963");

                    b.HasOne("TourismCMS.Models.POI", null)
                        .WithMany()
                        .HasForeignKey("Poiid")
                        .IsRequired()
                        .HasConstraintName("FK__POI_Categ__POIID__5441852A");
                });

            modelBuilder.Entity("TourismCMS.Models.AdminUser", b =>
                {
                    b.HasOne("TourismCMS.Models.Role", "Role")
                        .WithMany("AdminUsers")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__AdminUser__RoleI__4CA06362");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TourismCMS.Models.Menu", b =>
                {
                    b.HasOne("TourismCMS.Models.POI", "Poi")
                        .WithMany("Menus")
                        .HasForeignKey("Poiid")
                        .HasConstraintName("FK__Menu__POIID__5812160E");

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("TourismCMS.Models.VisitLog", b =>
                {
                    b.HasOne("TourismCMS.Models.POI", "POI")
                        .WithMany("VisitLogs")
                        .HasForeignKey("Poiid")
                        .HasConstraintName("FK__VisitLog__POIID__5BE2A6F2");

                    b.Navigation("POI");
                });

            modelBuilder.Entity("TourismCMS.Models.POI", b =>
                {
                    b.Navigation("Menus");

                    b.Navigation("VisitLogs");
                });

            modelBuilder.Entity("TourismCMS.Models.Role", b =>
                {
                    b.Navigation("AdminUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
